# Generated by Django 2.2.5 on 2019-10-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20191008_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='user',
        ),
    ]
