# Generated by Django 2.2.5 on 2019-09-25 20:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
