# Generated by Django 2.2.5 on 2019-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20190927_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_to_take',
            field=models.BooleanField(default=True),
        ),
    ]
